name: wild_radar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  badges: ^3.1.2
  http: 1.2.2
  flutter_dotenv: ^5.0.2  
  flutter_map_marker_cluster: ^1.4.0
  wildlife_api_connection:
    git:
      url: https://github.com/WildLife-NL/Wildlife-api-connection.git
      ref: "94d125c"
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/images/bizon.png
    - lib/assets/images/edelhert.jpg
    - lib/assets/images/bos.jpg
    - lib/assets/images/zwijn.png
    - lib/assets/env/.env

